### ISSUE TITLE
I have a problem with final downloads, client1 client 2 and game server directories are not created

### ISSUE THREAD

**Issue by wanwindwalker** [WatermelonModders/hearthmodanvilnew#1]
![image](https://user-images.githubusercontent.com/108946798/178042816-0b414859-7f3a-4b36-87bc-3dcb0b48693b.png)

**Comment by wanwindwalker** [comment]
![image](https://user-images.githubusercontent.com/108946798/178044254-fd98429d-1806-47f9-a188-2d7b44de800f.png)

**Comment by WatermelonModders** [comment]
Hi, first i'd like to say thanks for using my software. I updated host-ctl_ubuntu.sh, so redownload the software again and start over.  
If that doesn't work then use the repo I forked this from hearthmod. Link: https://github.com/hearthmod/hearthmod

Also, I'm really sorry you have this issue, I'm still working out some of the kinks with the software.

Hopefully this fixes your problem.
